<table class="table is-fullwidth">
    <thead>
    <tr>
        <th></th>
        <th>Name</th>
        <th>Country</th>
        <th>Country</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1</td>
        <td>Sachin</td>
        <td>India</td>
        <td>India</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Smith</td>
        <td>Australia</td>
        <td>India</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Joe Root</td>
        <td>England</td>
        <td>India</td>
    </tr>
    </tbody>
</table>
